"""
Central configuration — the ONLY place that reads .env / environment
variables. Every other module imports its settings from here, so config is
loaded exactly once and there is no hidden import-order coupling.
"""

import os

from dotenv import load_dotenv

load_dotenv()

# ── Chat LLM (any OpenAI-compatible endpoint: OpenRouter / Groq / NVIDIA …) ─
CHAT_API_MODEL = os.getenv("CHAT_API_MODEL", "openai/gpt-oss-20b")
CHAT_API_KEY = os.getenv("CHAT_API_KEY", "")
CHAT_API_URL = os.getenv("CHAT_API_URL", "")
# OpenRouter وحده: ترتيب مزوّدي النموذج نفسه حسب throughput يقلل زمن القوائم
# الطويلة من دون تغيير model slug أو السماح بموديل آخر.
CHAT_PROVIDER_SORT = os.getenv("CHAT_PROVIDER_SORT", "")

# مزوّد محادثة احتياطي (اختياري): يُستخدم تلقائياً حين يفشل الأساسي بخطأ
# مزوّد (402 تجاوز الحد / 429 / 5xx). في اختبار 440 يجب أن يبقى نموذج
# الاحتياط هو openai/gpt-oss-20b نفسه. فارغ = لا احتياطي.
CHAT_FALLBACK_URL = os.getenv("CHAT_FALLBACK_URL", "")
CHAT_FALLBACK_KEY = os.getenv("CHAT_FALLBACK_KEY", "")
CHAT_FALLBACK_MODEL = os.getenv("CHAT_FALLBACK_MODEL", "")

# ── Embeddings (Jina) ─────────────────────────────────────────────────────
EMBED_MODEL = os.getenv("EMBED_MODEL", "jina-embeddings-v3")
EMBED_API_KEY = os.getenv("EMBED_API_KEY", "")
EMBED_API_URL = os.getenv("EMBED_API_URL", "")

# ── Caching (in-process TTL + LRU) ────────────────────────────────────────
# Only the query-embedding cache is used: question hash → its deterministic
# vector.  The legacy public-answer cache object remains visible in stats for
# API compatibility but is never read or written.
CACHE_ENABLED = os.getenv("CACHE_ENABLED", "true").lower() == "true"
# User requirement: every final response must be generated by the LLM.  Keep
# deterministic embedding/retrieval caches, but never serve a cached answer
# when this flag is enabled.
# Product invariant: retrieval/embedding caches may accelerate evidence
# gathering, but a stored or Python-authored final answer is never served.
# Keep these constants non-configurable so a deployment environment cannot
# accidentally bypass the LLM.
LLM_ALWAYS_ANSWER = True
ANSWER_CACHE_ENABLED = False
CACHE_ANSWER_TTL = int(os.getenv("CACHE_ANSWER_TTL", "3600"))       # 1 hour
CACHE_ANSWER_MAXSIZE = int(os.getenv("CACHE_ANSWER_MAXSIZE", "512"))
CACHE_EMBED_TTL = int(os.getenv("CACHE_EMBED_TTL", "86400"))         # 24 hours
CACHE_EMBED_MAXSIZE = int(os.getenv("CACHE_EMBED_MAXSIZE", "2048"))

# ── Rate limiting (per fixed window) ──────────────────────────────────────
# Protects the LLM/embeddings from bursts and login from brute force. In-memory
# (per-process) for now; move to Redis when running multiple instances.
RATE_LIMIT_CHAT_PER_MIN = int(os.getenv("RATE_LIMIT_CHAT_PER_MIN", "30"))
RATE_LIMIT_LOGIN_PER_MIN = int(os.getenv("RATE_LIMIT_LOGIN_PER_MIN", "10"))

# ── Logging ───────────────────────────────────────────────────────────────
# DEBUG | INFO | WARNING | ERROR — consumed by app.log (one console handler).
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
TRACE_INCLUDE_QUERY_TEXT = os.getenv(
    "TRACE_INCLUDE_QUERY_TEXT", "false"
).lower() == "true"

# ── Authentication (JWT) ──────────────────────────────────────────────────
# Signs the session token issued at login. MUST be a strong secret set via
# .env in production — the default below is for local dev only (app.tokens
# logs a warning if it is still in use outside development).
JWT_SECRET = os.getenv("JWT_SECRET", "dev-insecure-change-me")
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_HOURS = int(os.getenv("JWT_EXPIRE_HOURS", "12"))

# Admin key for corpus-mutating ops (file upload/delete/reload, cache clear).
# Empty by default → those endpoints are DENIED until an admin key is set.
ADMIN_API_KEY = os.getenv("ADMIN_API_KEY", "")

# Public self-registration. True (demo default) lets a student create an
# account with a self-reported profile. Set FALSE in a real deployment so
# accounts are provisioned only from the enrollment system — closing anonymous
# subject squatting / account-flood (see security report findings 1 & 6).
ALLOW_PUBLIC_REGISTRATION = os.getenv("ALLOW_PUBLIC_REGISTRATION", "true").lower() == "true"

# Optional one-time bootstrap for the first administrator. There is no public
# admin-registration endpoint. Leave both empty after the account exists.
ADMIN_BOOTSTRAP_ID = os.getenv("ADMIN_BOOTSTRAP_ID", "")
ADMIN_BOOTSTRAP_PASSWORD = os.getenv("ADMIN_BOOTSTRAP_PASSWORD", "")
ADMIN_BOOTSTRAP_NAME = os.getenv("ADMIN_BOOTSTRAP_NAME", "مدير النظام")


def assert_secure_for_production() -> None:
    """Fail closed: refuse to run in production with a weak/default JWT secret,
    instead of quietly signing forgeable tokens. Dev/testing keep the default."""
    if API_ENV == "production" and (
        JWT_SECRET == "dev-insecure-change-me" or len(JWT_SECRET) < 32
    ):
        raise RuntimeError(
            "❌ JWT_SECRET ضعيف أو افتراضي في الإنتاج — عيّن سراً قوياً (≥32 حرفاً) في .env قبل التشغيل."
        )

# ── API layer (FastAPI) ───────────────────────────────────────────────────
# ENV switches docs/CORS defaults: "development" | "testing" | "production".
API_ENV = os.getenv("API_ENV", "development")
API_HOST = os.getenv("API_HOST", "127.0.0.1")
API_PORT = int(os.getenv("API_PORT", "8000"))
# Files uploaded before the RBAC catalog existed stay visible locally so the
# current chatbot keeps working. Production defaults to deny until an admin
# explicitly classifies and publishes each legacy collection.
LEGACY_UNCATALOGUED_FILES_PUBLIC = os.getenv(
    "LEGACY_UNCATALOGUED_FILES_PUBLIC",
    "true" if API_ENV != "production" else "false",
).lower() == "true"
# Comma-separated allowed origins for the frontend, e.g. "http://localhost:3000".
# "*" (dev default) must be replaced with the real frontend origin in production.
API_CORS_ORIGINS = [
    o.strip() for o in os.getenv("API_CORS_ORIGINS", "*").split(",") if o.strip()
]

# ── MongoDB ───────────────────────────────────────────────────────────────
MONGO_URI = os.getenv("MONGO_URI")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "iug_chatbot")
UPLOADED_DB_NAME = os.getenv("UPLOADED_DB_NAME", "uploaded_files")

# ── RAG / chat tuning ─────────────────────────────────────────────────────
TOP_K = 10
# أسئلة «ما التخصصات التي تقبلني بمعدل X؟» تجميعية: تحتاج جدول مفاتيح القبول
# كاملاً لا أقرب مقاطعه تشابهاً (top-K كان يعيد نسخ برامج كلية واحدة ويُسقط
# البقية). ما دام الجدول تحت هذا السقف يُرسل كله؛ فوق السقف نعود لبحث موسّع.
ADMISSION_TABLE_MAX_CHUNKS = int(os.getenv("ADMISSION_TABLE_MAX_CHUNKS", "150"))
# سقف أحرف سياق الاسترجاع (0 = بلا سقف). المفاتيح المجانية الصغيرة تسقط
# 402 «Prompt tokens limit exceeded» فوق سقفها — على بيئة كهذه عيّنه (مثلاً
# 6000) فتُقلَّم أضعف المقاطع بدل انفجار الطلب كله (سبب 13 سؤالاً بلا جواب
# في تقييم الـ90 على المفتاح المجاني).
MAX_CONTEXT_CHARS = int(os.getenv("MAX_CONTEXT_CHARS", "0"))

# ── Reranker (خطة التحسين م2 — خلف فلاغ حتى يثبت القياس جدواه) ────────────
# القوائم والأسئلة المركبة تحتاج تغطية أوسع بلا reranker؛ أما البحث الدقيق
# والمتابعات الملتبسة فيسترجع مرشحين أكثر ثم يعيد cross-encoder ترتيبهم.
# كلاهما محدودان كي لا يدفع كل سؤال كلفة زمنية/توكنية إضافية.
COVERAGE_TOP_K = int(os.getenv("COVERAGE_TOP_K", "16"))
RERANK_ENABLED = os.getenv("RERANK_ENABLED", "false").lower() == "true"
RERANK_URL = os.getenv("RERANK_URL", "https://api.jina.ai/v1/rerank")
RERANK_MODEL = os.getenv("RERANK_MODEL", "jina-reranker-v2-base-multilingual")
RERANK_CANDIDATES = int(os.getenv("RERANK_CANDIDATES", "20"))
# fail-open سريع: إن لم يجب المزود ضمن الميزانية نستخدم ترتيب RRF الموجود.
RERANK_TIMEOUT_SECONDS = float(os.getenv("RERANK_TIMEOUT_SECONDS", "2.5"))
RERANK_CIRCUIT_FAILURES = int(os.getenv("RERANK_CIRCUIT_FAILURES", "2"))
RERANK_CIRCUIT_COOLDOWN_SECONDS = float(
    os.getenv("RERANK_CIRCUIT_COOLDOWN_SECONDS", "60")
)
PIPELINE_V2_ENABLED = os.getenv("PIPELINE_V2_ENABLED", "true").lower() == "true"
# Product invariant: this deployment uses the bounded agent planner.  Keeping
# this non-configurable avoids a production environment silently falling back
# to a different retrieval path than the one evaluated in tests.
AGENTIC_RAG_ENABLED = True
RAG_PIPELINE_VERSION = "bounded-agentic-rag-v3"
HIERARCHICAL_CHUNKING_ENABLED = os.getenv(
    "HIERARCHICAL_CHUNKING_ENABLED", "true"
).lower() == "true"
EVIDENCE_CONTRACT_ENABLED = os.getenv(
    "EVIDENCE_CONTRACT_ENABLED", "true"
).lower() == "true"
PARENT_EXPANSION_MAX_CHUNKS = int(
    os.getenv("PARENT_EXPANSION_MAX_CHUNKS", "4")
)
# Product/UI invariant.  ``frontend/chat.js`` mirrors this value because the
# static client is intentionally build-tool free.
CHAT_TURN_LIMIT = 10
# الذاكرة القصيرة للمحادثة: آخر 5 أدوار فقط (FIFO)، كل دور يحمل متجه سؤاله
# المحسوب مرة واحدة عند الحفظ — لا يُعاد حسابه أبداً.
MAX_HISTORY = 5
# حد التشابه (cosine على متجهات مطبّعة) لاعتبار دور سابق «ذا صلة» بالسؤال
# الحالي فيُحقن في البرومت. الدور الأحدث يُحقن دائماً (استمرارية الحوار).
MEMORY_MIN_SIM = float(os.getenv("MEMORY_MIN_SIM", "0.45"))
# «نضارة» الدور: المتابعات القصيرة («أذكرهم»، «كم هيكلفني؟») تُسلسَل فقط على
# دورٍ أحدث من هذه المدة — السجل دائم عبر الأيام، وبدونها سؤالُ اليوم القصير
# كان يرث موضوعَ محادثة الأمس (ثبت حياً: «أذكرهم» أجابت بإيميلات رؤساء الأقسام
# من جلسة سابقة بدل أسماء الكليات).
MEMORY_FRESH_MINUTES = int(os.getenv("MEMORY_FRESH_MINUTES", "45"))
SIM_THRESHOLD = 0.25

# ── Hybrid retrieval (dense embeddings + lexical BM25, fused with RRF) ─────
# Lexical BM25 catches exact Arabic terms — fee numbers, course codes, names —
# that pure embedding similarity often misses. Reciprocal Rank Fusion merges
# the two rankings without fragile score normalization.
HYBRID_ENABLED = True
RRF_K = 60          # RRF damping constant (standard default)
BM25_K1 = 1.5       # term-frequency saturation
BM25_B = 0.75       # document-length normalization

# ── Embedding-index persistence ───────────────────────────────────────────
# Embeddings are expensive (Jina API call per chunk) and deterministic for a
# given (model, chunk-text). Persisting them turns an ~80s cold start into a
# near-instant load and stops re-billing Jina on every run. Keyed by a
# fingerprint of (model + chunk texts), so it self-invalidates on any change.
#   INDEX_BACKEND = "disk"  → .index_cache/ files (great locally)
#                 = "mongo" → embedding_index collection (survives ephemeral
#                             disks, e.g. Render redeploys)
INDEX_BACKEND = os.getenv("INDEX_BACKEND", "disk")
INDEX_CACHE_DIR = os.getenv("INDEX_CACHE_DIR", ".index_cache")

# ── Session (chat-history) persistence ────────────────────────────────────
#   SESSION_BACKEND = "mongo"  → chat_sessions collection (survives restarts)
#                   = "memory" → in-process (lost on restart; used by tests)
SESSION_BACKEND = os.getenv("SESSION_BACKEND", "mongo")
LLM_MAX_TOKENS = 450
# القوائم/الأسئلة المركبة تحتاج جواباً أطول. البدء بالميزانية الصحيحة يمنع
# إعادة الطلب كاملاً عند finish_reason=length (Q096 احتاج 3 طلبات: 450→900→1800).
LLM_COVERAGE_MAX_TOKENS = int(os.getenv("LLM_COVERAGE_MAX_TOKENS", "1400"))
LLM_MULTIPART_MAX_TOKENS = int(os.getenv("LLM_MULTIPART_MAX_TOKENS", "1200"))
# University facts should not vary merely because the provider sampled a
# different wording path.  Evidence can still change the answer; sampling may
# not change sensitive values.
LLM_TEMPERATURE = 0.0
LLM_TOP_P = 1.0
_LLM_SEED_RAW = os.getenv("LLM_SEED", "").strip()
LLM_SEED = int(_LLM_SEED_RAW) if _LLM_SEED_RAW else None
# Reasoning models (e.g. gpt-oss) spend part of max_tokens on hidden
# "reasoning" before any visible answer. استخراج حقائق RAG مهمة مقيدة لا
# تحتاج تفكيراً مفتوحاً؛ minimal يقلل زمن/توكنات التفكير ويحفظ ميزانية النص.
LLM_REASONING_EFFORT = os.getenv("LLM_REASONING_EFFORT", "minimal")
EMBED_BATCH_SIZE = 64
HISTORY_TURNS_IN_PROMPT = 6

# Collections that must NEVER be indexed as RAG content. Auth/identity/PII
# collections (password hashes, tokens, user records) would otherwise become
# searchable chunks and could leak into an LLM answer — so they are ALWAYS
# excluded, on top of anything added via .env.
_ALWAYS_EXCLUDE_FROM_RAG = {
    "students_auth", "refresh_tokens", "users",  # auth/identity/PII
    "chat_sessions", "embedding_index",           # our own persistence collections
    "file_catalog", "managed_file_versions", "audit_log",
}
RAG_EXCLUDE_COLLECTIONS = _ALWAYS_EXCLUDE_FROM_RAG | {
    c.strip() for c in os.getenv("RAG_EXCLUDE_COLLECTIONS", "").split(",") if c.strip()
}
