"""Bounded Agentic-RAG policy.

The agent chooses retrieval tools and retry budgets, but it never writes the
user-facing answer.  Tool choice is deterministic and auditable; the final
response (including refusals and safe fallbacks) is always generated by the
chat LLM.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

from app.conversation_frame import ConversationFrame, QueryPlan
from app.domain_router import DomainRoute


@dataclass(slots=True)
class BoundedAgentPlan:
    context_mode: str
    route: str
    tools: list[str]
    use_structured_lookup: bool
    use_hybrid_retrieval: bool
    use_reranker: bool
    use_parent_expansion: bool
    allow_evidence_retry: bool
    ask_for_clarification: bool
    max_retrieval_attempts: int = 2
    max_generation_attempts: int = 3
    reason: str = ""

    def as_metadata(self) -> dict[str, Any]:
        return asdict(self)


def plan_rag_actions(
    plan: QueryPlan,
    frame: ConversationFrame,
    domain_route: DomainRoute,
    *,
    has_authoritative_evidence: bool,
    safety_directive: bool,
) -> BoundedAgentPlan:
    """Choose a small, closed set of tools for this turn.

    There are no open-ended loops and no arbitrary tool calls.  One initial
    retrieval plus one evidence-coverage retry is the hard ceiling.
    """
    tools: list[str] = ["context_classifier"]
    if domain_route.structured_first or has_authoritative_evidence:
        tools.append("structured_evidence")

    ask_for_clarification = bool(frame.ambiguous and not frame.reference)
    if ask_for_clarification:
        tools.append("clarification_gate")

    if safety_directive:
        use_hybrid = False
        use_reranker = False
        use_parent = False
        allow_retry = False
        tools.append("policy_evidence")
        reason = "privacy/safety policy supplies the only evidence"
    else:
        # An exact structured resolution can stand alone.  Compound questions
        # still need text retrieval for their remaining parts.
        use_hybrid = not (has_authoritative_evidence and not plan.is_compound)
        use_reranker = bool(use_hybrid and domain_route.use_reranker)
        use_parent = bool(
            use_hybrid
            and (
                plan.is_followup
                or plan.is_compound
                or plan.is_list_question
                or plan.needs_query_expansion
            )
        )
        allow_retry = bool(use_hybrid and plan.route == "advanced_rag")
        if use_hybrid:
            tools.extend(["dense_search", "bm25", "rrf"])
        if use_reranker:
            tools.append("reranker")
        if use_parent:
            tools.append("parent_expansion")
        if allow_retry:
            tools.append("evidence_retry")
        reason = domain_route.reason

    return BoundedAgentPlan(
        context_mode=plan.context_mode,
        route=domain_route.mode,
        tools=list(dict.fromkeys(tools)),
        use_structured_lookup=bool(
            domain_route.structured_first or has_authoritative_evidence
        ),
        use_hybrid_retrieval=use_hybrid,
        use_reranker=use_reranker,
        use_parent_expansion=use_parent,
        allow_evidence_retry=allow_retry,
        ask_for_clarification=ask_for_clarification,
        reason=reason,
    )


__all__ = ["BoundedAgentPlan", "plan_rag_actions"]
